source "https://rubygems.org"

group :frontend do
  gem 'bundler',             '~> 1.13.6'
  gem 'compass',             '~> 1.0.1'
  gem 'sass',                '~> 3.4.5'
  gem 'scss-lint',           '~> 0.33.0'
  gem 'bootstrap-sass',      '~> 3.3.6'
  gem 'font-awesome-sass',   '~> 4.6.2'
  gem 'sass-rails',          '>= 3.2'
  gem 'compass-import-once', '~> 1.0.5'
end